CREATE TABLE TB_BOARD ( 
  SEQ_NO     NUMBER        NOT NULL, 
  TITLE      VARCHAR2 (200)  NOT NULL, 
  CLSS       CHAR (2), 
  AUTHOR     VARCHAR2 (50)  NOT NULL, 
  PASSWD     VARCHAR2 (8), 
  EMAIL      VARCHAR2 (50), 
  AFILE      VARCHAR2 (100), 
  REG_DATE   CHAR (8), 
  READ_CNT   NUMBER, 
  CTNT       CLOB, 
  LVL_NO     VARCHAR2 (500)  NOT NULL, 
  LVL        NUMBER        NOT NULL, 
  SORT_SEQ   NUMBER        NOT NULL, 
  R_DATE     DATE, 
  ANSWER     CHAR (1), 
  DEL_KEY    CHAR (1), 
  LOCATION   VARCHAR2 (100), 
  FILE_NAME  VARCHAR2 (100), 
  CONSTRAINT TB_SIDEPT_QNA_PK PRIMARY KEY ( SEQ_NO ) 
);

CREATE INDEX IDX_BOARD_LVL_NO ON 
  TB_BOARD(LVL_NO);

CREATE INDEX IDX_BOARD_SEQ_SORT ON 
  TB_BOARD(SORT_SEQ, LVL_NO);
  
  
CREATE TABLE TB_BBS_MAIN (
  BBS_ENAME   VARCHAR2 (20), 
	TOTAL_ROW NUMBER, 
	CONSTRAINT TB_BBS_MAIN_PK PRIMARY KEY ( BBS_ENAME )
);


INSERT INTO TB_BBS_MAIN 
(
  BBS_ENAME,
 	TOTAL_ROW
) VALUES (
	'TB_BOARD',
	0
);  